python main.py \
--sigma 5.0 \
--clamp tanh \
--n_normaugs 4 \
--n_augs 1 \
--normmincrop 0.1 \
--normmaxcrop 0.1 \
--frontview \
--frontview_std 4 \
--clipavg view \
--lr_decay 0.9 \
--clamp tanh \
--normclamp tanh \
--maxcrop 1.0 \
--save_render \
--seed 78942387 \
--save_render \
--frontview_center 5.4 -0.5 \
--colordepth 2 \
--normdepth 2 \
--n_iter 1500 \
--learning_rate 0.005 \
--output_dir evaluation_no_blend_new \
--experiment_group evaluation_no_blend_new \
--width 32 \
--depth 2 \
--model_name Text2MeshMultiMLP \
--loss_name multi_mlp_loss \
--do_backward_masking \
--biased_views \
--dataset PartGlotData \
--sample 601 \
--prompt "snowflake pattern arm" \
--prompt "metallic leg" \
--prompt "honeycomb back" \
--prompt "wooden seat" 
